---
title: "__TITLE__"
author: "matricaria.suaveolens@gmail.com"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
format: 
  revealjs:
    embed-resources: true
bibliography:
  - bibliography.bib
  - tools.bib
---

```{r setup, echo=F, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path='figures/', cache = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries}
#| label: libraries
#| message: false
#| cache: false
#| include: false

library(readr)
#library(feather)
#library(data.table)
#library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)
library(kfigr)
library(knitr)
#library(DT)
#library(reactable)
library(grateful)
library(patchwork)
```

```{r constants}
#| label: constants
GTDB_TAXRANKS    <- c('domain', 'phylum', 'class', 'order', 'family', 'genus', 'species')
ORDERED_TAXRANKS <- c('domain', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species', 'strain', 'subspecies')
```

```{r read-data}
#| label: read-data
```

## Slide 1

## References
