---
title: "__TITLE__"
author: "daniel.lundin@lnu.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
    bookdown::html_document2:
        toc: yes
        toc_depth: 1
        toc_float:
            collapse: yes
        fig_caption: yes
        number_sections: no
        code_folding: hide
    pdf_document:
        fig_caption: yes
        fig_height: 9
        fig_width: 8
        number_sections: yes
        toc: yes
bibliography: 
    - bibliography.bib
    - grateful-refs.bib
biblio-style: apalike
link-citations: yes
---

```{r setup, echo=F, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path='figures/', cache = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries, message=F, cache = FALSE}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(feather))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(dtplyr))
suppressPackageStartupMessages(library(dplyr, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(kfigr))
suppressPackageStartupMessages(library(knitr))
library(grateful)
```

```{r constants}
```

```{r read-data}
```

# Introduction

Example citation [@author].

# Materials and Methods

## R and packages

The version of R and versions of packages used in this project can be found in
(`r figr('cite-packages', T, type = 'Table')).

```{r cite-packages, cache = FALSE}
cite_packages(output = "table") %>%
  kable()
```

# Results

# Discussion

# References
